### PR TITLE
Autumn-aton Support

### PR DESCRIPTION
**Pull request by trewqpoiuuy**
Added support for autumn-aton, including:

- Gathering both leg and both arm upgrades
- Sending him to Sonofa Beach for barrels of gunpowder
- Farming The Oasis with him afterwards

### CODE REVIEW

**Comment by Kasekopf** [comment]
Thanks for the PR!

Is sending to the smut orcs and to the oasis worth it here? We don't normally spend any adventures in either during the casual.

Is there another rightarm1 zone we already use? How much is the oasis worth compared to the ~4k~ 8k from an autumn dollar?

**Comment by trewqpoiuuy** [comment]
For the right arm, it looks like the only outdoor/mid zones we normally spend adventures in are the three peaks. Prioritizing the bridge and the first twin peaks task if you have fallbot seems like a good solution here, I'll test that after rollover and make the change.

I chose the oasis because that's where garbo likes to send him, so it's nice to have unlocked if you're doing the casual leg last. The expected value of a trip with both arms and one acuity (from sonofa beach) is about 1 drum machine (3k), 1/3 of a mojo filter (~2.5k), and 1/6 of an autumn dollar (~600), because you get a random consumable after you've picked up the pendant from sonofa beach. 

Autumn dollars are possibly a better target, but the only underground/mid zones we visit are the ones in the cyrpt, which close well before the end of the run. We could delay finishing the cyrpt until last, which may not be a bad idea - we could send him to the nook to farm evil eyes and potentially save a spit/nostalgia/envy. I'll play with the routing and get back to you.

**Comment by trewqpoiuuy** [comment]
Made the changes described above, and my test run went smoothly! Thanks for the suggestions

**Comment by Kasekopf** [comment]
Looks great! The last thing I notice is that it should send the autumnaton to some always-available location if none of the listed locations are available. Just as some safeguard, otherwise the script may get stuck if someone runs loopcasual in a weird character state. After that it should be ready to merge.

**Comment by trewqpoiuuy** [comment]
Done!

**Comment by Kasekopf** [comment]
Great, thanks!

**Pull request merged**
